spring:
  application:
    name: api-gateway
  cloud:
   gateway:
    discorery:
     locator:
      enable: true
      lower-case-service-id: true
server:
  port: ${PORT:8765}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka} 

